language: java

jdk:
  - oraclejdk8

dist: trusty

sudo: false

script: mvn clean verify


deploy:
  provider: releases
  prerelease: true
#  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: "target/*.jar"
  skip_cleanup: true
  on:
      tags: true
